-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMDs6TCOwXb1yKpPw
HTzuhFjZxwXr4SU9pxwdusBHqTGgCgYIKoZIzj0DAQehRANCAARE2vHuG7Lwde46
Zh4c8jv1kY7Cl4BIQtZEFftlVAjDg2FLGoPows4yWXVbAdYyrel69UjWP40DiIhe
zhotYB2/
-----END PRIVATE KEY-----